name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
      run: |
        docker build . --file Dockerfile --tag tayko/cwb110-project:latest
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push tayko/cwb110-project:latest
